apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: fastapi-app
      context: app
manifests:
  kustomize:
    paths:
    - k8s
portForward:
  - resourceType: service
    resourceName: ingress-nginx-controller
    namespace: ingress-nginx
    port: 80
    localPort: 8080
